[package]
name = "rolyng_parser_c"
description = "parser of c language for educational purpose"
version = "0.1.1"
edition = "2021"
license = "GPL-3.0-only"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
peg = "0.8.2"
